config/routes.rb
Cem::Application.routes.draw do
  
  resources :ng_states do  
    collection do
      get 'add'
      get 'remove'
    end    
  end

  

   resources :participants do
     collection do
       get 'export_to_excel'
     end
   end

 

  resources :event_partners do
    collection do
      get 'add'
      get 'remove'
    end
  end
  

   resources :dashboard, :only=>[:index] ,:via => 'get'

  resources :event_speakers do
    collection do
      get 'add'
      get 'remove'
    end
  end

  resources :event_images
  resources :events do
    
    resources :event_images , :event_speakers
  end
  resources :sessions 
  
  resources :users do
    
    collection do 
      get 'change_my_password'
    end
  end

  
  

   
   root :to => 'events#show'
   
  
  match 'cem' => 'public#home'
  match 'about' => 'public#about'
  match 'contact' => 'public#contact'
  match 'services' => 'public#services'
  match 'login' => 'sessions#new' 
  match "/logout" => "sessions#destroy"
  match "dashboard" => "dashboard/index"
  

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
    before_filter :login_required
    layout :user_layout
  def index
    
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.haml
<div class="container" style="margin-top:40px;">
<h2 style="color:#ccc;" align="center">System Dashboard <hr class="slim"></h2>
<div class="row-fluid">
<div class="span6 well">
<h3>System Summary</h3> 
<div class="accordion" id="accordion2">
<div class="accordion-group">
<div class="accordion-heading">
<a class="accordion-toggle btn btn-red tyl" data-toggle="collapse" data-parent="#accordion2" href="#pct"><i class="icon-chevron-right icon-white"></i> 
Participants
</a>
</div>
<div id="pct" class="accordion-body collapse in">
<div class="accordion-inner">
<a href="#{new_participant_url}" class="btn btn-lblue"><i class="icon-white icon-plus-sign"></i> Register Participant</a>
<a href="#{participants_url}" class="btn btn-blue"><i class="icon-white icon-th-large"></i> Manage Participants</a>
</div>
</div>
</div>



<!--<div class="accordion-group">
<div class="accordion-heading">
<a class="accordion-toggle btn btn-red tyl" data-toggle="collapse" data-parent="#accordion2" href="#evtt"><i class="icon-chevron-right icon-white"></i> 
Event Officials
</a>
</div>
<div id="evtt" class="accordion-body collapse">
<div class="accordion-inner">
<a href="#" class="btn btn-success"><i class="icon-white icon-plus-sign"></i> Register Official(s)</a>
<a href="#" class="btn btn-inverse"><i class="icon-white icon-th-large"></i> Manage Official</a>
</div>


</div>
</div>-->
              

        




<div class="accordion-group">
<div class="accordion-heading">
<a class="accordion-toggle btn btn-red tyl" data-toggle="collapse" data-parent="#accordion2" href="#evttt"><i class="icon-chevron-right icon-white"></i> 
Cemproactii Staff
</a>
</div>
<div id="evttt" class="accordion-body collapse">
<div class="accordion-inner">
<a href="#{new_user_path}" class="btn btn-success"><i class="icon-white icon-plus-sign"></i> Add staff</a>
<a href="#{users_url}" class="btn btn-inverse"><i class="icon-white icon-th-large"></i> Manage Staff</a>
</div>
</div>
</div>
<div class="accordion-group">
<div class="accordion-heading">
<a class="accordion-toggle btn btn-red tyl" data-toggle="collapse" data-parent="#accordion2" href="#evt"><i class="icon-chevron-right icon-white"></i> 
Events
</a>
</div>
<div id="evt" class="accordion-body collapse">
<div class="accordion-inner">
<a href="#{new_event_path}" class="btn btn-success"><i class="icon-white icon-plus-sign"></i> Add Events</a>
<a href="#{new_event_image_path}" class="btn btn-success"><i class="icon-white icon-plus-sign"></i> Add Event Images</a>

<a href="#{new_event_speaker_path}" class="btn btn-success"><i class="icon-white icon-plus-sign"></i> Add Event Speaker(s)</a>
%p
  %p
  <a href="#{new_event_partner_path}" class="btn btn-success"><i class="icon-white icon-plus-sign"></i> Add Event Partner(s)</a>

<a href="#{events_url}" class="btn btn-inverse"><i class="icon-white icon-th-large"></i> Manage Events</a>
</div>
</div>
</div> 


%br
%br
<!--<div class="accordion-group">
<div class="accordion-heading">
<a class="accordion-toggle btn btn-red tyl" data-toggle="collapse" data-parent="#accordion2" href="#evtttt"><i class="icon-chevron-right icon-white"></i> 
Events Financials
</a>
</div>
<div id="evtttt" class="accordion-body collapse">
<div class="accordion-inner">
<a href="#{new_event_path}" class="btn btn-success"><i class="icon-white icon-plus-sign"></i> Add Financial</a>
<a href="#{events_url}" class="btn btn-inverse"><i class="icon-white icon-th-large"></i> Manage Financials</a>
</div>


</div>
</div>  -->             
</div>
</div>
<div class="span6 well">
<h3>Date & Time </h3>
= time_tag Time.now
</div>
<div class="nosrednahabo">&nbsp;</div>                                      
</div>
</div>
= render "shared/social_media_links"