config/routes.rb
Cem::Application.routes.draw do
  
  resources :ng_states do  
    collection do
      get 'add'
      get 'remove'
    end    
  end

  

   resources :participants do
     collection do
       get 'export_to_excel'
     end
   end

 

  resources :event_partners do
    collection do
      get 'add'
      get 'remove'
    end
  end
  

   resources :dashboard, :only=>[:index] ,:via => 'get'

  resources :event_speakers do
    collection do
      get 'add'
      get 'remove'
    end
  end

  resources :event_images
  resources :events do
    
    resources :event_images , :event_speakers
  end
  resources :sessions 
  
  resources :users do
    
    collection do 
      get 'change_my_password'
    end
  end

  
  

   
   root :to => 'events#show'
   
  
  match 'cem' => 'public#home'
  match 'about' => 'public#about'
  match 'contact' => 'public#contact'
  match 'services' => 'public#services'
  match 'login' => 'sessions#new' 
  match "/logout" => "sessions#destroy"
  match "dashboard" => "dashboard/index"
  

end

app/models/participant.rb
# == Schema Information
#
# Table name: participants
#
#  id                      :integer          not null, primary key
#  name                    :string(255)
#  title                   :string(255)
#  event_id                :integer
#  day_in                  :string(255)
#  date_in                 :date
#  day_out                 :string(255)
#  date_out                :date
#  ticket_cost             :string(255)
#  discounted              :string(255)
#  uni_id                  :string(255)
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  firstname               :string(255)
#  lastname                :string(255)
#  ng_state_id             :integer
#  ng_lg_id                :integer
#  phone                   :string(255)
#  email                   :string(255)
#  address                 :text
#  office                  :text
#  photo_file_name         :string(255)
#  photo_content_type      :string(255)
#  photo_file_size         :integer
#  photo_updated_at        :datetime
#  othername               :string(255)
#  gender                  :string(255)
#  occupation              :string(255)
#  position_currently_held :string(255)
#  lgward                  :string(255)
#  closing_ceremony        :string(255)
#  event_recordings        :string(255)
#  attending_dinner        :string(255)
#  followup_info           :string(255)
#  payment_mode            :string(255)
#  phone2                  :string(255)
#

class Participant < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
  belongs_to :ng_state
  attr_accessor :user_id 
  
  attr_accessible :phone2,:closing_ceremony, :lgward,:othername ,:gender,:occupation,:position_currently_held,:event_recordings,:attending_dinner,:followup_info,:payment_mode,:photo , :phone, :email,:address, :office, :date_in,:ng_state_id, :user_id,:ng_lg_id,:firstname,:lastname ,:date_out, :day_in, :day_out, :discounted, :event_id, :name, :ticket_cost, :title, :uni_id

  validates :uni_id , :presence => true,
                      :uniqueness => {:case_sensitive =>false}
  validates :event_id , :presence => true
  validates :ticket_cost , :presence => true
  
  has_attached_file  :photo ,:styles => { :medium => "200x160>", :thumb => "100x100>" },:url => "/uploads/participants_photos/:id/:style/:basename.:extension",
    :path =>":rails_root/public/uploads/participants_photos/:id/:style/:basename.:extension"
 
 before_save :check_record 
 
 
 private
 
 def check_record
   
   if new_record?
      ex  = Participant.count(:conditions =>{
        :event_id => event_id , 
        :firstname => firstname ,
        :lastname => lastname,
        :uni_id => uni_id,
        :ng_state_id => ng_state_id,
        #:email => email,
        :phone => phone,
        :phone2 => phone2,
       # :photo_file_name => photo_file_name 
         
        })
      return false if ex > 0 
    end
 
   
   
 end
end

app/controllers/participants_controller.rb
require 'open-uri'
class ParticipantsController < ApplicationController
  before_filter :login_required , :except=>[:index,:show]
  layout :user_layout
  def index
     if !params[:sort].blank?
     sort = params[:sort]
     
     else
     sort = "event_id asc"  
    end
    if params[:event_id]
      
     @participants = Participant.where(:event_id=> params[:event_id]).paginate(:page=>params[:page],:per_page =>20).order(sort)
     @event_title = Event.find_by_id(params[:event_id]).name
    else
    @participants = Participant.paginate(:page=>params[:page],:per_page =>20).order(sort)
     end
  
  end

  def new
    
     @events = Event.select("id, name").where("name is not null")
      @states =NgState.select("id, state").where("state is not null")
    @participant = Participant.new
  end

  def create
   @uni_id = generateRandom
   
    if request.post?
      @participant = Participant.new params[:participant]
      @participant.uni_id = @uni_id if @participant.uni_id.blank?
      
      if @participant.save
        
        flash[:notice] = "Successfully Registered Participant!"
        
      else
        erro = ""
        
        
         @participant.errors.full_messages.each do |m|
           
          erro += m + "<br/>"
            
       
         end
        flash[:error] = "Unable to register Participant!<br/>" + erro
       
        @events = Event.select("id, name").where("name is not null")
      @states =NgState.select("id, state").where("state is not null")
        render :new
        
      end
      
     
    end
     redirect_to new_participant_url
      return false
  end

  def edit
    
    @participant = Participant.find(params[:id])
    @events = Event.select("id, name").where("name is not null")
    @states =NgState.select("id, state").where("state is not null")
    render :new
  
  end

  def update
    @participant  =  Participant.find(params[:id])
    if @participant.update_attributes(params[:participant])
       flash[:notice] = "Successfully Updated the Participant: #{params[:participant][:firstname]}"
       redirect_to new_participant_url
       return false
        
    else
      @participant = Participant.find(params[:id])
    @events = Event.select("id, name").where("name is not null")
    @states =NgState.select("id, state").where("state is not null")
    render :new
    end
       
  end

  def show
  end

  def destroy
    if Participant.find(params[:id]).destroy()
      flash[:notice] = "successfully deleted"
      
    else
      flash[:error] = "unable to delete!"
      
    end
    redirect_to participants_url
    return false
  end
  
  
  def export_to_excel
   if !params[:type]
     @clients =Participant.find(:all,:conditions => {"event_id" => params[:event_id]}) 
   end
   
  require 'spreadsheet'
  respond_to do |format|
      format.pdf
      format.xls {
        clients = Spreadsheet::Workbook.new
        list = clients.create_worksheet :name => 'All Participants'
        list.row(0).concat %w[Title Firstname  Lastname Othername Gender State LG]
        list.row(0).height = 30
        #list.column(0).width = 10
       # list.column(1).width = 20
       # list.column(2).width = 20
       # list.column(3).width = 20
       
         
        @clients.each_with_index { |client, i|
          list.row(i+1).push client.title ,client.firstname , client.lastname , client.othername, client.gender, client.ng_state.state, client.lgward, client.created_at.to_date
          
       
        }
        header_format = Spreadsheet::Format.new :color => :blue, :weight => :bold ,:align =>:center
        list.row(0).default_format = header_format
        #output to blob object
        blob = StringIO.new("")
        clients.write blob
        #respond with blob object as a file
        send_data blob.string, :type => :xls, :filename => "Participants.xls"
      }
end
    
 end
  private
  
  def generateRandom
    
     r=Random.new
    
   # @uni_id =  r.rand(000100..999999)
   @uni_id =  r.rand((Time.now.nsec-1)..Time.now.nsec)
    uni_id = @uni_id.to_s
     
     st= "" 
     st += uni_id[r.rand(0..5)]
    uid = uni_id.chop.chop.chop
    
    if Participant.count(:conditions=>{:uni_id =>uid}) > 0
     
     generateRandom
     
   end
      return uid
      
      
    
    
    
  end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/create.html.erb
<h1>Participants#create</h1>
<p>Find me in app/views/participants/create.html.erb</p>

app/views/participants/destroy.html.erb
<h1>Participants#destroy</h1>
<p>Find me in app/views/participants/destroy.html.erb</p>

app/views/participants/edit.html.haml
%style{:type=>"text/css"}
  select{width:90px;}
<div class="container-narrow" style="margin-top:40px;">
<h2 style="color:#ccc;" align="center">Edit Registration <hr class="slim"></h2>
<div class="row-fluid">
<div class="span12 well">

= form_for @participant , :html =>{:multipart => true} do |f|
  <fieldset>
  <legend>Please fill this form</legend>
  
  <div class="input-prepend well-small">
  <span class="add-on">Event &nbsp;&nbsp;&nbsp;</span>
  = collection_select(:participant ,:event_id ,@events , :id , :name, :include_blank =>true)
   
  </div>
  <div class="input-prepend well-small">
  <span class="add-on"> Participant's Title &nbsp;&nbsp;&nbsp;</span>
  = f.select :title ,[["",""],["Mr","Mr"],["Mrs","Mrs"],["Miss","Miss"],["Dr","Dr"], ["Chief","Chief"]].sort
   
  </div>
  
  
  <div class="well-small">
  <label>Participant's Firstname &nbsp;&nbsp;&nbsp;</label>
  = f.text_field :firstname, :placeholder=>"Enter Participant's name"
  </div>
  
  <div class="well-small">
  <label>Participant's' Lastname &nbsp;&nbsp;&nbsp;</label>
  = f.text_field :lastname, :placeholder=>"Enter Participant's name"
  </div>
  
  <div class="well-small">
  <label>Participant's' Email &nbsp;&nbsp;&nbsp;</label>
  = f.text_field :email, :placeholder=>"Enter Participant's email"
  </div>
  
  <div class="well-small">
  <label>Participant's' Phone &nbsp;&nbsp;&nbsp;</label>
  = f.text_field :phone, :placeholder=>"Enter Participant's phone"
  </div>
  
  <div class="well-small">
  <label>Participant's' Address &nbsp;&nbsp;&nbsp;</label>
  = f.text_field :address, :placeholder=>"Enter Participant's address"
  </div>
  
  <div class="well-small">
  <label>Participant's' Office &nbsp;&nbsp;&nbsp;</label>
  = f.text_field :office, :placeholder=>"Enter Participant's office"
  </div>
  <div class="well-small">
  <label>Ticket Price(NGN) &nbsp;&nbsp;&nbsp;</label>
  = f.text_field :ticket_cost, :value =>"130,000", :placeholder=>"Enter Participant's name"
  </div>
  
  <div class="well-small">
  <label>Discount rate(%) &nbsp;&nbsp;&nbsp;</label>
  = f.text_field :discounted, :value =>"0" ,:placeholder=>"0%"
  </div>
  = f.hidden_field :user_id , :value => @current_user.id
   
  <div class="input-prepend well-small">
  <span class="add-on">State &nbsp;&nbsp;&nbsp;</span>
  = collection_select(:participant ,:ng_state_id ,@states , :id , :state, :include_blank =>true)
   
  </div>

  <div class="well-small">
  <label> date Out</label>
  
  = f.date_select :date_in,:start_year=>Time.now.year,:use_short_month=>true,:order=>[:day,:month,:year], :html=>{:class=>'input-small '}
  </div>
  
  <div class="well-small ">
  <label>Date Out</label>
  
  = f.date_select :date_out,:start_year=>Time.now.year,:use_short_month=>true,:order=>[:day,:month,:year], :html=>{:class=>'input-small ' , :style=>"width:1em;"}
  </div>
  
  
  
  
  
  <hr class="soften">
  
  <button class="btn btn-submit"><i class="icon-white icon-plus-sign"></i> Modify</button>
  </fieldset>
   
  </div></div>

 
</div>

app/views/participants/index.html.haml
<div class="container" style="margin-top:40px;">
<h2 style="color:#ccc;" align="center">Manage Participants <hr class="slim"></h2>
<div class="row-fluid">
<div class="span12 well">
<table class="table table-striped table-hover table-bordered">
<caption><strong>Total Participants &rarr; #{@participants.size} <hr></strong>
- if !@event_title.blank?
  %span{:class=>"alert alert-success"}
    %strong Event &rarr;
    %strong= @event_title
</caption>
<tr>

<th>ID </th>
<th>
=link_to "Names" , participants_url(:sort=>"firstname asc")
</th>
<th>
=link_to "Phones" , "#" 
</th>
<th>
= link_to "Event \#",participants_url(:sort=>"event_id desc")
</th>
<th>
= link_to "State" , participants_url(:sort=>"ng_state_id asc")
</th>
%td
  = link_to "Mode of Payment" ,"#"
<th>Actions </th>
</tr>
- @participants.each do |p|
  %tr
    %td= p.uni_id
    %td= p.firstname + " " + p.lastname
    
    %td= p.phone
    %td= link_to p.event.id , participants_url(:event_id =>p.event_id)
    %td= p.ng_state.state
    %td= p.payment_mode
    %td
      <div class="btn-group">
      <!--<a href="#" class="btn btn-small fancybox"><i class="icon-comment"></i> SMS </a> -->
      <!--<a href="#" class="btn btn-small  fancybox btn-blue"><i class="icon-white icon-envelope"></i> Email </a> -->
      <a href="#{edit_participant_url(p.id)}" class="btn btn-small btn-success"><i class="icon-white icon-edit"></i> Edit </a>
      <a href="#{participant_url(p.id)}" data-method="delete" data-confirm="Delete Participant?" class="btn btn-small btn-red"><i class="icon-white icon-trash"></i> Delete </a>
      </div> 
   
</table>

%div
  =link_to "Register Participant" , "#{new_participant_url}" ,:class=>"btn btn-lblue"
  = link_to "Export for Excel", "#" ,:class=>"btn btn-lblue"
= render "shared/paginate"

                   
                    
</div>
<div class="nosrednahabo">&nbsp;</div>                                      
</div>
</div>

app/views/participants/new.html.haml
%style{:type=>"text/css"}
  select{width:90px;}
<div class="container-medium" style="margin-top:40px;">
<h2 style="color:#ccc;" align="center">New Participant <hr class="slim"></h2>
<div class="row-fluid">
<div class="span12 well1">
%div
  %strong
    #{image_tag "/OfficialLogo.fw.png",:width =>"170" ,:height => "80",:style=>"margin:0 12em 0 40%;"}
= form_for @participant , :html =>{:multipart => true} do |f|
  <fieldset>
  <legend style="font-size:28px;">P a r t i c i p a n t s  &nbsp;&nbsp; R e g i s t r a t i o n  &nbsp;&nbsp;  F o r m</legend>
  %p
    Please fill in the required information accordingly. 
    -#We would advise you fill it out in Capital letters to aid easy data entry into our database.
    -#The form is divided into 3 sections according to the type of information required.
  %p
    On no account would the Senate Committee on States and Local Government Administration disclose your details to third party individuals or organizations. 
    %code This registration process is strictly for logistics and inventory purposes only.
  
  %caption
    %strong Section 1: Bio Data
  %p This section covers the provision of personal information for use by the Senate Committee on States and Local Government Administration. Please note that the names you give here are the same names that would appear on the final certificate to be issues at the end of the conference.
  <div class="input-prepend well-small">
  <span class="add-on">Event &nbsp;&nbsp;&nbsp;</span>
  = collection_select(:participant ,:event_id ,@events , :id , :name, :include_blank =>false)
   
  </div>
  <div class="input-prepend well-small">
  <label>Title &nbsp;&nbsp;&nbsp;</label>
  -#= f.select :title ,[["",""],["Mr","Mr"],["Mrs","Mrs"],["Miss","Miss"],["Dr","Dr"], ["Chief","Chief"]].sort
  = f.text_field :title 
  </div>
  
  
  <div class="well-small">
  <label> Firstname &nbsp;&nbsp;&nbsp;</label>
  = f.text_field :firstname, :placeholder=>"Enter Participant's firstname"
  </div>
  
  <div class="well-small">
  <label> Surname &nbsp;&nbsp;&nbsp;</label>
  = f.text_field :lastname, :placeholder=>"Enter Participant's surname"
  </div>
  
  <div class="well-small">
  <label> Other Names &nbsp;&nbsp;&nbsp;</label>
  = f.text_field :othername, :placeholder=>"Enter Participant's other names"
  </div>
  
  <div class="well-small">
  <label> Sex &nbsp;&nbsp;&nbsp;</label>
  = f.text_field :gender, :placeholder=>"Enter Participant's name"
  </div>
  
  <div class="input-prepend well-small">
  <span class="add-on">State &nbsp;&nbsp;&nbsp;</span>
  = collection_select(:participant ,:ng_state_id ,@states , :id , :state, :include_blank =>true)
   
  </div>
  
  <div class="well-small">
  <label> Local Government &nbsp;&nbsp;&nbsp;</label>
  = f.text_field :lgward, :placeholder=>"Enter Local Government"
  </div>
  
  <div class="well-small">
  <label> Occupation &nbsp;&nbsp;&nbsp;</label>
  = f.text_field :occupation, :placeholder=>"Enter Participant's Occupation"
  </div>
  
  <div class="well-small">
  <label> Position Currently Held &nbsp;&nbsp;&nbsp;</label>
  = f.text_field :position_currently_held, :placeholder=>"Enter Participant's Position"
  </div>
  <div>
  %caption
    %strong Section 2:  Contact Information
  
  %p
    This section covers information necessary for follow-up correspondence and notifications of future events and publications by the Senate Committee on States and Local Government Administration

  </div>
  <div class="well-small">
  <label>Office  Address &nbsp;&nbsp;&nbsp;</label>
  = f.text_field :address, :placeholder=>"Enter Office address"
  </div>
  <div class="well-small">
  <label>Telephone  1 &nbsp;&nbsp;&nbsp;</label>
  = f.text_field :phone, :placeholder=>"Phone"
  </div>
  
  <label>Telephone  2 &nbsp;&nbsp;&nbsp;</label>
  = f.text_field :phone, :placeholder=>""
  </div>
  
  <div class="well-small">
  <label>Email  Address &nbsp;&nbsp;&nbsp;</label>
  = f.text_field :email, :placeholder=>""
  </div>
  
  <div>
  %caption
    %strong Section 3:  Conference Options
    %p
      -#Please tick the most appropriate option.

  </div>
  <div>
  <label> Payment Mode?  &nbsp;&nbsp;&nbsp;</label>
  - @modes = [["Bank Draft","Bank Draft"],["Cash","Cash"],["Prepaid","Prepaid"]]
  = f.select :payment_mode , @modes ,:include_blank =>true
  </div>
  <div>
  <label> Would you be attending the closing ceremony?  &nbsp;&nbsp;&nbsp;</label>
  %span Yes
  = f.radio_button :closing_ceremony , :value => 'Yes'
  
  %span No
  = f.radio_button :closing_ceremony , :value => 'No'
  </div>
  
  <div>
  <label> Would you be interested in receiving follow-up information after the conference? &nbsp;&nbsp;&nbsp;</label>
  %span Yes
  = f.radio_button :followup_info , :value => 'Yes'
  
  %span No
  = f.radio_button :followup_info , :value => 'No'
  </div>
  
  <div>
  <label> Would you be participating in the dinner lunch?  &nbsp;&nbsp;&nbsp;</label>
  %span Yes
  = f.radio_button :attending_dinner , :value => 'Yes'
  
  %span No
  = f.radio_button :attending_dinner , :value => 'No'
  </div>
  
  <div>
  <label> Would you like a copy of the recordings of this seminar?    &nbsp;&nbsp;&nbsp;</label>
  %span Yes
  = f.radio_button :event_recordings , :value => 'Yes'
  
  %span No
  = f.radio_button :event_recordings , :value => 'No'
  </div>
   
  
  
  -#<div class="well-small">
  -#<label>Ticket Price(NGN) &nbsp;&nbsp;&nbsp;</label>
  = f.hidden_field :ticket_cost, :value =>"130,000"
  -#</div>
  
  <div class="well-small">
  
  = f.hidden_field :discounted, :value =>"0" ,:placeholder=>"0%"
  </div>
  = f.hidden_field :user_id , :value => @current_user.id
   
  

  -#<div class="well-small">
  -#<label> date Out</label>
  
  -#= f.date_select :date_in,:start_year=>Time.now.year,:use_short_month=>true,:order=>[:day,:month,:year], :html=>{:class=>'input-small '}
  -#</div>
  
  -#<div class="well-small ">
  -#<label>Date Out</label>
  
  -#= f.date_select :date_out,:start_year=>Time.now.year,:use_short_month=>true,:order=>[:day,:month,:year], :html=>{:class=>'input-small ' , :style=>"width:1em;"}
  -#</div>  
  <hr class="soften"/>
  
  <button class="btn btn-submit"><i class="icon-white icon-plus-sign"></i> Register</button>
  </fieldset>
</div>

</div></div>

app/views/participants/show.html.erb
<h1>Participants#show</h1>
<p>Find me in app/views/participants/show.html.erb</p>

app/views/participants/update.html.erb
<h1>Participants#update</h1>
<p>Find me in app/views/participants/update.html.erb</p>