config/routes.rb
Cem::Application.routes.draw do
  
  resources :ng_states do  
    collection do
      get 'add'
      get 'remove'
    end    
  end

  

   resources :participants do
     collection do
       get 'export_to_excel'
     end
   end

 

  resources :event_partners do
    collection do
      get 'add'
      get 'remove'
    end
  end
  

   resources :dashboard, :only=>[:index] ,:via => 'get'

  resources :event_speakers do
    collection do
      get 'add'
      get 'remove'
    end
  end

  resources :event_images
  resources :events do
    
    resources :event_images , :event_speakers
  end
  resources :sessions 
  
  resources :users do
    
    collection do 
      get 'change_my_password'
    end
  end

  
  

   
   root :to => 'events#show'
   
  
  match 'cem' => 'public#home'
  match 'about' => 'public#about'
  match 'contact' => 'public#contact'
  match 'services' => 'public#services'
  match 'login' => 'sessions#new' 
  match "/logout" => "sessions#destroy"
  match "dashboard" => "dashboard/index"
  

end

app/views/shared/_auth_menu.html.haml
<div class="navbar navbar-inverse navbar-fixed-top">
<div class="navbar-inner">
<div class="container">
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</a>
<a class="brand" href="./">
= image_tag "logo.fw.png"
</a>
<div class="nav-collapse collapse">           
<ul class="nav">
<li class="divider-vertical"></li>
<li><a href="#{dashboard_path}"><i class="icon32 icon-red icon-gear"></i> System Dashboard</a></li>
<li class="divider-vertical"></li>
<li><a href="#{participants_url}"><i class="icon32 icon-red icon-users"></i> Participants</a></li>
<li class="divider-vertical"></li>
<li><a href="#{events_url}"><i class="icon32 icon-red icon-bookmark"></i> Events</a></li>
<li class="divider-vertical"></li>            
</ul>
<ul class="nav pull-right">
<li class="divider-vertical"></li>
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown">
-#=image_tag "images/bii.jpg" 
Hi #{current_user.username} <b class="caret"></b></a>
<!---->
<ul class="dropdown-menu">
<li>
<div class="row-fluid" style="padding:10px;">
 
= image_tag "/img/biii.jpg" , :class=>"left"
= @current_user.username
</div>
</li>
<li class="divider"></li>
<li><a href="#{change_my_password_users_url}">Change My Password</a></li>

<li class="divider"></li>
<li><a href="#{logout_url}">Logout</a></li>
</ul>
</li>
</ul>
</div>
</div>
</div>
</div>

app/views/shared/_eventswall.html.haml
<ul class="media-list">
- if @events.blank?
  <li class="media">
  <a class="pull-left" href="#">
  <img class="media-object" data-src="holder.js/64x64">
  </a>
  <div class="media-body">
  <h4 class="media-heading"> Nothing Found in our events archive</h4>
  %p &nbsp;  ...
  <!--<p class="pull-right"><span><em>June 4, 2013 | 3:00pm</em></span></p> -->
  <p class="pull-right"><span><em> 
  = time_tag Date.today
  | #{Time.zone.now.hour} : #{Time.zone.now.min}
  </em></span></p> 
  </div>
  </li>
- else
  - @events.each do |e|
    <li class="media">
    <a class="pull-left" href="#">
    
    = image_tag "#{e.logo.url(:thumb)}" , :width=>"80" , :height =>"100"
    </a>
    <div class="media-body">
    <h4 class="media-heading"> #{link_to(e.name, event_url(e.id))}</h4>
    <p class="pull-right"><span> 
    = time_tag e.start_date
    | #{e.start_time.strftime("%H:%M")}
    </span></p> 
    </div>
    </li>
    
    
                
</ul>
<a href="#{events_url}" class="btn btn-submit btn-block btn-small"><i class="icon-white icon-plus-sign"></i> view all </a>

app/views/shared/_footer.html.haml
<hr class="light">
<div class="footer">
<div class="container">
<p class="muted credit pull-left">CemProactii &copy; 2013 </p>
<p class="pull-right muted"><a href="http://www.leproghrameen.com" target="_blank">Designed by Le Proghrammeen Solutions</a> </p>
</div>
</div>

app/views/shared/_newswall.html.haml
<div class="span4 well mxh">
<h3 align="center">News <hr class="soften"></h3>
<ul class="media-list">
<!--<li class="media">                    
<img class="pull-left media-object" data-src="holder.js/120x128">
<div class="media-body">
<h4 class="media-heading">Event heading</h4>
Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras  ...
<p class="pull-left"><a href="#" class="btn btn-small btn-inverse"><i class="icon-white icon-plus"></i> Detail</a></p> 
</div>                    
</li>-->
<li class="media">                    
<img class="pull-left media-object" data-src="holder.js/120x128">
<div class="media-body">
<h4 class="media-heading">Cemproactii News</h4>
%p Nothing found in our news archive  ...
<p class="pull-left"><a href="#" class="btn btn-small btn-inverse"><i class="icon-white icon-plus"></i> Detail</a></p> 
</div>                    
</li>
</ul>
<hr class="soften">
<a href="#" class="btn btn-submit btn-block btn-small"><i class="icon-white icon-plus-sign"></i> view all </a>
</div>

app/views/shared/_paginate.html.erb
<div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @users %>
    </div>
    <%= will_paginate nil, :container => false %>
  </div>

app/views/shared/_public_menu.html.haml
<div class="container">
<div class="navbar navbar-inverse ff7">
<div class="navbar-inner">
<div class="container">
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</a>

<div class="nav-collapse collapse">
<p class="navbar-text pull-right">
<a href="#{login_url}" class="navbar-link" style="font-size:19pt;"><i class="icon32 icon-red icon-user"></i>Login</a>
</p>
<ul class="nav">             
<li class="active"><a href="#{cem_url}"><i class="icon-white icon-home"></i></a></li>
<li class="divider-vertical"></li>
<li><a href="#{about_url}">About Us</a></li>
<li class="divider-vertical"></li>
<li><a href="#{services_url}">Our Services</a></li>
<li class="divider-vertical"></li>
<li><a href="#{events_url}">Events</a></li>
<li class="divider-vertical"></li>
<li><a href="#{contact_url}">Contact Us</a></li>              
</ul>

</div>
</div>
</div>
</div>
</div>

app/views/shared/_slider.html.haml
<div class="container">
<div class="frx well ff3 ff4">
<div id="slider" class="sl-slider-wrapper">
<div class="sl-slider">       
<div class="sl-slide" data-orientation="horizontal" data-slice1-rotation="-25" data-slice2-rotation="-25" data-slice1-scale="2" data-slice2-scale="2">
<div class="sl-slide-inner">
<div class="bg-img bg-img-1"></div>
<h2>Positioning Local Governments as hubs of National Transformation</h2>
<blockquote><p>#{link_to "Read more" , "#",:class=>"btn btn-submit btn-block btn-small",:style=>"width:7em;"}.</p><cite>Date: May 13th, 2013 | 9:00am</cite></blockquote>
</div>
</div>

<div class="sl-slide" data-orientation="vertical" data-slice1-rotation="10" data-slice2-rotation="-15" data-slice1-scale="1.5" data-slice2-scale="1.5">
<div class="sl-slide-inner">
<div class="bg-img bg-img-2"></div>
<h2>Positioning Local Governments as hubs of National Transformation</h2>
<blockquote><p>#{link_to "Read more" , "#",:class=>"btn btn-submit btn-block btn-small",:style=>"width:7em;"}.</p><cite>Date: May 13th, 2013 | 9:00am</cite></blockquote>
</div>
</div>

<div class="sl-slide" data-orientation="horizontal" data-slice1-rotation="3" data-slice2-rotation="3" data-slice1-scale="2" data-slice2-scale="1">
<div class="sl-slide-inner">
<div class="bg-img bg-img-3"></div>
<h2>Positioning Local Governments as hubs of National Transformation</h2>
<blockquote><p>#{link_to "Read more" , "#",:class=>"btn btn-submit btn-block btn-small",:style=>"width:7em;"}.</p><cite>Date: May 13th, 2013 | 9:00am</cite></blockquote>
</div>
</div>

<div class="sl-slide" data-orientation="vertical" data-slice1-rotation="-5" data-slice2-rotation="25" data-slice1-scale="2" data-slice2-scale="1">
<div class="sl-slide-inner">
<div class="bg-img bg-img-4"></div>
<h2>Positioning Local Governments as hubs of National Transformation</h2>
<blockquote><p>#{link_to "Read more" , "#",:class=>"btn btn-submit btn-block btn-small",:style=>"width:7em;"}.</p><cite>Date: May 13th, 2013 | 9:00am</cite></blockquote>
</div>
</div>

<div class="sl-slide" data-orientation="horizontal" data-slice1-rotation="-5" data-slice2-rotation="10" data-slice1-scale="2" data-slice2-scale="1">
<div class="sl-slide-inner">
<div class="bg-img bg-img-5"></div>
<h2>Positioning Local Governments as hubs of National Transformation</h2>
<blockquote><p>#{link_to "Read more" , "#",:class=>"btn btn-submit btn-block btn-small",:style=>"width:7em;"}.</p><cite>Date: May 13th, 2013 | 9:00am</cite></blockquote>
</div>
</div>
</div>
<nav id="nav-dots" class="nav-dots">
<span class="nav-dot-current"></span>
<span></span>
<span></span>
<span></span>
<span></span>
</nav>
</div>
</div>
</div>

app/views/shared/_social_media_links.html.haml
<div class="frx">            
<div class="gbar">
<div class="container">
<div class="row-fluid">
<div class="span12" align="right">Online Connect <a href="" title="Find us on facebook">
= image_tag "facebook.fw.png" 
</a>
<a href="" title="Follow us on twitter">
= image_tag "Twitter.fw.png"
</a></div>
</div>  
</div>
</div>      
</div>

app/views/shared/_subscribe_to_newsletter.html.haml
<h3 align="center">Subscribe to Our Events <hr class="soften"></h3>
<form>
<div class="input-prepend">
<span class="add-on">Phone</span>
<input id="prependedInput" type="text" placeholder="Your Phone Number">
</div>
<hr>
<div class="input-prepend">
<span class="add-on">Email&nbsp;</span>
<input id="prependedInput" type="text" placeholder="Your Email Address">
</div>
<div class="nosrednahabo">&nbsp;</div>
<button class="btn btn-submit"><i class="icon-white icon-chevron-right"></i> Subscribe</button>
</form>