config/routes.rb
Cem::Application.routes.draw do
  
  resources :ng_states do  
    collection do
      get 'add'
      get 'remove'
    end    
  end

  

   resources :participants do
     collection do
       get 'export_to_excel'
     end
   end

 

  resources :event_partners do
    collection do
      get 'add'
      get 'remove'
    end
  end
  

   resources :dashboard, :only=>[:index] ,:via => 'get'

  resources :event_speakers do
    collection do
      get 'add'
      get 'remove'
    end
  end

  resources :event_images
  resources :events do
    
    resources :event_images , :event_speakers
  end
  resources :sessions 
  
  resources :users do
    
    collection do 
      get 'change_my_password'
    end
  end

  
  

   
   root :to => 'events#show'
   
  
  match 'cem' => 'public#home'
  match 'about' => 'public#about'
  match 'contact' => 'public#contact'
  match 'services' => 'public#services'
  match 'login' => 'sessions#new' 
  match "/logout" => "sessions#destroy"
  match "dashboard" => "dashboard/index"
  

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                  :integer          not null, primary key
#  name                :string(255)
#  start_date          :date
#  start_time          :time
#  end_time            :time
#  end_date            :date
#  location            :string(255)
#  about               :text
#  user_id             :integer
#  created_by          :string(255)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  logo_file_name      :string(255)
#  logo_content_type   :string(255)
#  logo_file_size      :integer
#  logo_updated_at     :datetime
#  participants_number :integer
#  tickteting          :text
#

class Event < ActiveRecord::Base
  
  attr_accessible :about, :logo,:tickteting, :participants_number,:created_by, :end_date, :end_time, :location, :name, :start_date, :start_time, :user_id
  has_many :event_images
  has_many :event_speakers
  has_many :event_partners
  has_many :participants
  has_attached_file :logo ,:styles => { :medium => "300x300>", :thumb => "200x160>" },:url => "/uploads/events_logo/:id/:style/:basename.:extension",
    :path =>":rails_root/public/uploads/events_logo/:id/:style/:basename.:extension"
 
 validates  :name,  :presence => true,
                          
                         :uniqueness => {:case_sensitive=>false}
                         
 validates :user_id , :presence => true
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  before_filter :login_required , :except=>[:index,:show]
  layout :user_layout
  before_filter :check_staff? , :except => [:show,:index]
  
  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id],:include=>[:event_speakers,:event_images])
    
  end

  def create
    @event = Event.new(params[:event])
    if @event.save
    
    @event_id = @event.id
    es = params[:data][:event_speaker]
    es.delete_if{|f| f[:fullname].blank?}
    
    es.each do |s|
      s[:event_id] = @event_id
      s[:user_id] = current_user.id
      e_v_s = EventSpeaker.new s if !s[:fullname].nil?
      e_v_s.save
    end
    
    flash[:notice] = "Successfully saved new item"
    
    redirect_to events_url and return
    
    else
      flash[:error] = "Unable to save"
      render :new
    end
   
  end

  def update
    if request.put?
      
     @newspub = @model= Event.find(:first,:conditions=>{:id =>params[:id]})
     if @newspub.nil?
       flash[:error] =" Invalid Selection detected. "
       redirect_to  events_path
       return nil
     end
       #find(:first,:conditions=>{"user_id"=>current_user.id,"id"=>params[:newspub][:id]})
      
      if (params[:event][:logo])
              
       @newspub.logo=nil
       @newspub.save
       
      end      
        
       params[:event][:user_id] = current_user.id
       # @newspub = @model= Newspub.find(:first,:conditions=>{:user_id =>current_user.id,:id =>params[:newspub][:id]})
      
       if @newspub.update_attributes(params[:event])
       flash[:notice] = "Successfully Updated the Event: #{params[:event][:title]}"
       
       elsif !params[:event][:logo]
        
         params[:event][:user_id] = current_user.id
         # @newspub = @model= Newspub.find(:first,:conditions=>{:user_id =>current_user.id,:id =>params[:newspub][:id]})
         @newspub.update_attributes(params[:event])
         flash[:notice] = "Successfully Updated the Event  #{params[:event][:title]}"        
       else
         flash[:error] = "Failed to update the Event"  
      end
      
      redirect_to events_path
      end
  end

  def index
    
    @events = Event.paginate(:page=>params[:page],:per_page =>10)
  end

  def show
    if params[:id].blank? and request.host == "subcaster.local"
      params[:id] = '18'
    elsif params[:id].blank? and request.host != "subcaster.local"
      params[:id] = '2'
    
    end
    @event = Event.find(params[:id],:include =>[:event_images, :event_speakers])
  end

  def destroy
 
      @event = Event.find_by_id(params[:id])
      session[:e] = @event
      #@event.logo = nil
       
       if @event.destroy
       flash[:notice] = "Successfully deleted item"
      else
        flash[:error] = "unable to delete item"
      
    end
    redirect_to events_url and return
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/Copy of _speakers.html.haml
<div class="span6 well">
<h3>Speakers & Dignitaries </h3>
<div class="scrollspy sbar p10">
<div class="topbar">
<span id="close" class="btn back"><i class="icon-chevron-left"></i> Back</span>
<h3 id="name"></h3>
</div>
<div class="wrapit">
<ul id="tp-grid" class="tp-grid">

- @event.event_speakers.reverse.each do |d|
  <li data-pile="#{d.event.name}">
  <span class="tp-info"><span>#{d.fullname}</span></span>
  = image_tag(d.photo.url(:thumb),:alt=>"")
   
  - if signed_in?
    %p
      <a class="btn" href="#{edit_event_speaker_url(d.id)}"><i class="icon-pencil"></i></a>   
      = link_to "<i class=\"icon-trash\"></i>".html_safe, event_speaker_url(d.id) ,:method => :delete,:class=>"btn" ,:data=>{:confirm=>"Delete #{d.fullname} ?",:title => "Delete #{d.fullname}"}
  </li>

</ul>
</div>
</div>

app/views/events/_speakers.html.haml
<div class="span6 well">
<h3>Speakers & Dignitaries </h3>
<div id="imgholder">
- @event.event_speakers.reverse.each do |d|
 
  = image_tag(d.photo.url(:medium),:alt=>"#{link_to(d.fullname,d.url,:target=>'_blank')} ")
  -#= link_to d.fullname ,"#"
   
  - if signed_in?
    %p
      <a class="btn" href="#{edit_event_speaker_url(d.id)}"><i class="icon-pencil"></i></a>   
      = link_to "<i class=\"icon-trash\"></i>".html_safe, event_speaker_url(d.id) ,:method => :delete,:class=>"btn" ,:data=>{:confirm=>"Delete #{d.fullname} ?",:title => "Delete #{d.fullname}"}
 
</div>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.haml
%style{:type=>"text/css"}
  select{width:90px;}
<div class="container-narrow" style="margin-top:40px;">
<h2 style="color:#ccc;" align="center">New Event <hr class="slim"></h2>
<div class="row-fluid">
<div class="span12 well">

= form_for @event , :html =>{:multipart => true} do |f|
  <fieldset>
  <legend>Please fill this form</legend>
  <div class="input-prepend well-small">
  <span class="add-on">Title &nbsp;&nbsp;&nbsp;</span>
  = f.text_field :name , :placeholder=>"Enter event name",:id=>"prependedinput"
   
  </div>
  
  <div class="well-small">
  <label>Event Detail&nbsp;&nbsp;&nbsp;</label>
  = f.text_area :about, :rows=>5, :class=>"span10",:placeholder=>"Enter Event Content"
  </div>
   
  <div class="input-prepend well-small">
  <span class="add-on">Location &nbsp;&nbsp;&nbsp;</span>
  
  = f.text_field :location , :placeholder =>"Enter event location/address"
  </div>
  
      
  <div class="input-prepend well-small">
  <span class="add-on">Speakers &nbsp;&nbsp;</span>
  
  %br
  - if !@event.event_speakers.empty? 
    - @event.event_speakers.each do |sp|
      <div class="well-small"></div>
      <label>#{ sp.fullname}</label>    
      = image_tag sp.photo.url(:thumb)
      = link_to "Edit Speaker" , edit_event_speaker_url(sp.id)
    
  - else
    %br
    = link_to "Add Speaker(s)" , new_event_speaker_url(:event_id=>@event.id), :target =>"_blank",:class=>" btn btn-submit"
     
  
  %br
  %br
    
  
  <!--<a href="#" class="btn btn-red btn-small pull-right"><i class="icon-white icon-plus"></i> Add Speakers</a>-->
  <hr class"soften">
  
  <div class="input-prepend well-small">
  <span class="add-on">Number of Participants &nbsp;&nbsp;&nbsp;</span>
  
  = f.text_field :participants_number,:class=>"span4", :placeholder=>"Enter number"
  </div>                                
  
  <div class="input-prepend well-small">
  <span class="add-on">Event Images &nbsp;&nbsp;</span>
  
  %br
  - if !@event.event_images.empty? 
    
    = link_to "#{@event.event_images.size}(s) Images" , event_images_url(:event_id=>@event.id), :class=>" btn btn-submit"
  - else
    %br
    = link_to "Add Event Image" , new_event_image_url(:event_id=>@event.id),:target =>"_blank", :class=>" btn btn-submit"
 
  
  %br
  %br
    
  
  
  </div> 
  <div class="well-small">
  <label>Event Logo/Banner</label>
  
  
  = image_tag @event.logo.url(:thumb)
  %br
  = f.file_field :logo
  
  </div>
  <div class="input-prepend well-small">
  <label>Event Ticketing</label>
  
  = f.text_area :tickteting,:rows=>5, :class=>"span10"

  </div>
  <div class="well-small">
  <label>Start date</label>
  
  = f.date_select :start_date,:start_year=>Time.now.year,:use_short_month=>true,:order=>[:day,:month,:year], :html=>{:class=>'input-small '}
  </div>
  
  <div class="well-small ">
  <label>End Date</label>
  
  = f.date_select :end_date,:start_year=>Time.now.year,:use_short_month=>true,:order=>[:day,:month,:year], :html=>{:class=>'input-small ' , :style=>"width:1em;"}
  </div>
  
  
  <div class="well-small">
  <label>Start time(local)</label>
  
  = f.time_select :start_time, :html=>{:class=>'input-small '}
  
  </div>
  
  <div class="well-small">
  <label>End time(local)</label>
  
  = f.time_select :end_time,:html=>{:class=>'input-small '}
  </div>
  
  <hr class="soften">
  = f.hidden_field :user_id , :value => @current_user.id
   
  <button class="btn btn-submit"><i class="icon-white icon-plus-sign"></i> Update Event</button>
  </fieldset>
   
  </div></div>
  
 
</div>

app/views/events/index.html.haml
<div class="container" style="margin-top:40px;">
<div class="row-fluid">
<div class="span12 well">
<h2 align="center">Events <hr class="soften"></h2>
<div class="row-fluid">
<div class="span12">
<!--<h3>Events <hr class="tw"></h3>-->
<ul class="thumbnails">

- @events.each do |e|
  
  <li class="span3" style="margin:4px;">
  <div class="thumbnail tbw" align="center">
  <a href="#{event_url(e)}">
  -#= image_tag "2.jpg", :alt=>"" 
  = image_tag e.logo.url(:thumb)
  </a> <div class="description">  
  <p>#{e.name}</p>
  <p>Date: #{time_tag e.start_date} 
  | 
  - if !e.start_time.blank?
    Time: #{e.start_time.strftime("%H:%M")}
  </p>
  <p>Location: #{e.location} </p>
  </div>
  %p
  = link_to "Read more",event_url(e.id), :class=>"btn btn-submit  btn-block btn-small btn-success"
   
  </div> 
  - if signed_in?
    %p
      <a class="btn"  data-toggle="modal" href="#"><i class="icon-list-alt"></i></a>
      <a class="btn" href="#{edit_event_url(e.id)}"><i class="icon-pencil"></i></a>   
      = link_to "<i class=\"icon-trash\"></i>".html_safe, event_url(e.id) ,:method => :delete,:class=>"btn" ,:data=>{:confirm=>"Delete #{e.name} ?",:title => "Delete #{e.name}"}
     
 
</ul>
<hr class="soften">
<div class="pagination" align="center">
<!--<ul>
<li><a href="#">Prev</a></li>
<li><a href="#">1</a></li>
<li><a href="#">2</a></li>
<li><a href="#">3</a></li>
<li><a href="#">4</a></li>
<li><a href="#">Next</a></li>
</ul>-->
= render "shared/paginate"
</div>


</div>
</div>
</div>

app/views/events/new.html.haml
%style{:type=>"text/css"}
  select{width:90px;}
<div class="container-medium" style="margin-top:40px;">
<h2 style="color:#ccc;" align="center">New Event <hr class="slim"></h2>
<div class="row-fluid">
<div class="span12 well">

= form_for @event , :html =>{:multipart => true} do |f|
  <fieldset>
  <legend>Please fill this form</legend>
  <div class="input-prepend well-small">
  <span class="add-on">Title &nbsp;&nbsp;&nbsp;</span>
  = f.text_field :name , :placeholder=>"Enter event name",:id=>"prependedinput"
   
  </div>
  
  <div class="well-small">
  <label>Event Detail&nbsp;&nbsp;&nbsp;</label>
  = f.text_area :about, :rows=>5, :class=>"span10",:placeholder=>"Enter Event Content"
  </div>
  = f.hidden_field :user_id , :value => @current_user.id
   
  <div class="input-prepend well-small">
  <span class="add-on">Location &nbsp;&nbsp;&nbsp;</span>
  
  = f.text_field :location , :placeholder =>"Enter event location/address"
  </div>
  
      
  <div class="input-prepend well-small">
  <span class="add-on">Speakers &nbsp;&nbsp;</span>
  
  %br
  %br
  <input id="prependedInput" type="text" name="data[event_speaker][][fullname]" placeholder="Enter event speakers">
  <div class="well-small"></div>
  <label>Photo</label>
  <input type="file" name="data[event_speaker][][photo]" id=""> 
  
  %br
  %br
  <input id="prependedInput" type="text" name="data[event_speaker][][fullname]" placeholder="Enter event speakers">
  <div class="well-small"></div>
  <label>Photo</label>
  <input type="file" name="data[event_speaker][][photo]" id=""> 
  
  
  %br
  %br
  <input id="prependedInput" type="text" name="data[event_speaker][][fullname]" placeholder="Enter event speakers">
  <div class="well-small"></div>
  <label> Photo</label>
  <input type="file" name="data[event_speaker][][photo]" id=""> 
  
  <!--<a href="#" class="btn btn-red btn-small pull-right"><i class="icon-white icon-plus"></i> Add Speakers</a>-->
  <hr class"soften">
  
  <div class="input-prepend well-small">
  <span class="add-on">Number of Participants &nbsp;&nbsp;&nbsp;</span>
  = f.text_field :participants_number,:class=>"span4", :placeholder=>"Enter number"

  </div>                                
  
  <div class="well-small">
  <label>Event Logo/Banner</label>
  
  = f.file_field :logo
  </div>
  
  <div class="input-prepend well-small">
  <label>Event Ticketing</label>
  
  = f.text_area :tickteting,:rows=>5, :class=>"span10"

  </div>
  <div class="well-small">
  <label>Start date</label>
  
  = f.date_select :start_date,:start_year=>Time.now.year,:use_short_month=>true,:order=>[:day,:month,:year], :html=>{:class=>'input-small '}
  </div>
  
  <div class="well-small ">
  <label>End Date</label>
  
  = f.date_select :end_date,:start_year=>Time.now.year,:use_short_month=>true,:order=>[:day,:month,:year], :html=>{:class=>'input-small ' , :style=>"width:1em;"}
  </div>
  
  
  <div class="well-small">
  <label>Start time(local)</label>
  
  = f.time_select :start_time, :html=>{:class=>'input-small '}
  
  </div>
  
  <div class="well-small">
  <label>End time(local)</label>
  
  = f.time_select :end_time,:html=>{:class=>'input-small '}
  </div>
  
  <hr class="soften">
  
  <button class="btn btn-submit"><i class="icon-white icon-plus-sign"></i> Create Event</button>
  </fieldset>
   
  </div></div>

 
</div>

app/views/events/show.html.haml
<div class="container" style="margin-top:40px;">
<div class="row-fluid">
<div class="span6 well">
<div class="breadcrumb"><a href="#{events_url}">Events</a> &laquo; Event Details </div>
<h3 class="soften">#{@event.name} <hr></h2>                    
- if !@event.about.blank?
  

  = @event.about.html_safe 
  
- else
  = @event.about
<hr>
<h3>Location</h3>
%p
  = @event.location

<h3>Date and Time</h3>
%p
  = time_tag @event.start_date
  = @event.start_time.strftime("%H:%M")
  \-
  = time_tag @event.end_date
  = @event.end_time.strftime("%H:%M.")
  
<hr>
<h3>Hotel Booking & Reservation</h3>
%p  Hotels are available within Abuja at affordable rates for participants and delegates.
%p  Here are links  to recommended hotels for you 
%p= link_to "Nicon Luxury", "http://www.niconluxury.com" , :target=>"_blank"
%p= link_to "Transcorp Hotel Abuja", "http://www3.hilton.com/en/hotels/nigeria/transcorp-hilton-abuja-ABUHITW/index.html" , :target=>"_blank"
%p= link_to "Chelsea Hotel Abuja", "http://www.chelseahotelabuja.com" , :target=>"_blank"

<hr>
<h3>Downloads</h3>
%p= link_to "Workshop Time Table" ,"/Workshop_Schedule.pdf",:target=>"_blank"

<hr>
<h3>Paper Submission Deadline</h3>
%p May 3<sup>rd</sup>, 2013.

- if signed_in?
  %p
  <a class="btn" href="#{edit_event_url(@event.id)}"><i class="icon-pencil"></i></a>   
  = link_to "<i class=\"icon-trash\"></i>".html_safe, event_url(@event.id) ,:method => :delete,:class=>"btn" ,:data=>{:confirm=>"Delete #{@event.name} ?",:title => "Delete #{@event.name}"}
  <a href="#{new_event_path}" class="btn btn-success"><i class="icon-white icon-plus-sign"></i> Add Event</a>

</div>
= render "speakers"
<div class="row-fluid">
<div class="span12">
<h3>Event Ticketing <hr class="tw"></h3>
-#= image_tag "demoimg.jpg" ,:class=>"pull-right img-rounded img-polaroid"
- if !@event.tickteting.blank?
  = @event.tickteting.html_safe
- else
  = @event.tickteting
  

</div>                    
</div>
<hr class="soften">


                
</div> 
                
</div>


</div>



<div class="container well">

<h2 class="soften">Event Partners & Sponsors <hr></h2>                    
- @event.event_partners.reverse.each do |e|
  = image_tag(e.logo.url(:thumb),:title => e.name) 
  &nbsp; &nbsp; &nbsp;
  
  - if signed_in?
    %p
      <a class="btn" href="#{edit_event_partner_url(e.id)}"><i class="icon-pencil"></i></a>   
      = link_to "<i class=\"icon-trash\"></i>".html_safe, event_partner_url(e.id) ,:method => :delete,:class=>"btn" ,:data=>{:confirm=>"Delete #{e.name} ?",:title => "Delete #{e.name}"}

<hr>
</div>
= render "shared/social_media_links"

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>